from .user import User
from .faculty import Faculty
from .subject import Subject
from .room import Room
from .direction import Direction
from .study_form import StudyForm
from .semester import Semester
from .group import Group
from .student_profile import StudentProfile
from .professor_profile import ProfessorProfile
from .professor_contract import ProfessorContract
from .professor_workload import ProfessorWorkload
from .subject_assignment import SubjectAssignment
from .schedule import Schedule
from .lesson import Lesson
from .academic_year import AcademicYear
