from .user import user_router
from .auth import auth_router
from .faculty import faculty_router
from .direction import direction_router
from .group import group_router
from .room import room_router
from .subject import subject_router
from .subject_assignment import subject_assignment_router
from .schedule import schedule_router
from .semester import semester_router
from .professor_contract import professor_contract_router
from .professor_workload import professor_workload_router
from .study_form import study_form_router
from .lesson import lesson_router
from .academic_year import academic_year_router
