"""add number column to semester, group_semester assosiation table

Revision ID: 0c6cf4bf39c4
Revises: cbb22411dd5c
Create Date: 2025-08-12 10:54:51.352719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6cf4bf39c4'
down_revision: Union[str, None] = 'cbb22411dd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
