"""add color field to subject model

Revision ID: 870fe882a501
Revises: 28e3429b895d
Create Date: 2025-10-02 15:46:10.562682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870fe882a501'
down_revision: Union[str, None] = '28e3429b895d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_index(op.f('ix_room_number'), table_name='room')
    op.drop_table('room')
    op.drop_table('student_profile')
    op.drop_index(op.f('idx_group_time_conflict'), table_name='lesson')
    op.drop_index(op.f('idx_lesson_calendar'), table_name='lesson')
    op.drop_index(op.f('idx_lesson_subject_group'), table_name='lesson')
    op.drop_index(op.f('idx_room_time_conflict'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_table('faculty')
    op.drop_table('professor_profile')
    op.drop_table('academic_year')
    op.drop_table('professor_contract')
    op.drop_table('group')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('schedule')
    op.drop_table('direction')
    op.drop_table('study_form')
    op.drop_table('subject_assignment')
    op.drop_table('semester')
    op.drop_table('professor_workload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_workload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('study_form_id', sa.INTEGER(), nullable=False),
    sa.Column('contract_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_hours', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['professor_contract.id'], ),
    sa.ForeignKeyConstraint(['study_form_id'], ['study_form.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'study_form_id', name='uq_contract_study_form')
    )
    op.create_table('semester',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('academic_year_id', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.VARCHAR(length=6), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.CheckConstraint("period IN ('winter', 'summer')", name='semester_period_enum'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_assignment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workload_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('hours_per_subject', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['workload_id'], ['professor_workload.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workload_id', 'subject_id', name='uq_workload_subject')
    )
    op.create_table('study_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direction_id', sa.INTEGER(), nullable=False),
    sa.Column('form', sa.VARCHAR(length=9), nullable=False),
    sa.CheckConstraint("form IN ('part_time', 'full_time')", name='study_form_enum'),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('semester_id', sa.INTEGER(), nullable=False),
    sa.Column('direction_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=11), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=9), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'coordinator', 'user')", name='user_role_enum'),
    sa.CheckConstraint("user_type IN ('student', 'professor')", name='user_type_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('study_form_id', sa.INTEGER(), nullable=False),
    sa.Column('semester_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['study_form_id'], ['study_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('professor_profile_id', sa.INTEGER(), nullable=False),
    sa.Column('semester_id', sa.INTEGER(), nullable=False),
    sa.Column('total_hours', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['professor_profile_id'], ['professor_profile.user_id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_year',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_profile',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lesson',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.Column('is_online', sa.BOOLEAN(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('lesson_type', sa.VARCHAR(length=8), nullable=False),
    sa.CheckConstraint("lesson_type IN ('lecture', 'seminar', 'lab', 'practice')", name=op.f('lesson_type_enum')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['subject_assignment_id'], ['subject_assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_room_time_conflict'), 'lesson', ['room_id', 'date', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('idx_lesson_subject_group'), 'lesson', ['subject_assignment_id', 'group_id'], unique=False)
    op.create_index(op.f('idx_lesson_calendar'), 'lesson', ['schedule_id', 'date', 'start_time'], unique=False)
    op.create_index(op.f('idx_group_time_conflict'), 'lesson', ['group_id', 'date', 'start_time', 'end_time'], unique=False)
    op.create_table('student_profile',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_number'), 'room', ['number'], unique=1)
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('semester_id', sa.INTEGER(), nullable=False),
    sa.Column('direction_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
